# Generated by Django 3.2.12 on 2022-09-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yogidice', '0002_auto_20220927_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BggData',
            fields=[
                ('bgg_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bgg_code', models.BigIntegerField()),
                ('nick_name', models.CharField(max_length=50)),
                ('rating_user', models.FloatField()),
            ],
            options={
                'db_table': 'bgg_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('bgg_code', models.BigIntegerField()),
                ('contents', models.CharField(blank=True, max_length=500, null=True)),
                ('contents_img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty', models.FloatField()),
                ('max_players', models.IntegerField(blank=True, null=True)),
                ('max_time', models.CharField(blank=True, max_length=50, null=True)),
                ('min_players', models.IntegerField(blank=True, null=True)),
                ('min_time', models.CharField(blank=True, max_length=50, null=True)),
                ('playing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('publish_year', models.IntegerField()),
                ('rating_bl', models.FloatField()),
                ('rating_user', models.FloatField()),
                ('thumb_url', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=100)),
                ('title_kr', models.CharField(max_length=100)),
                ('youtube_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'board_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardGameCafe',
            fields=[
                ('cafe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'board_game_cafe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CafeGameList',
            fields=[
                ('game_list_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cafe_game_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('cate_group_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('mechanism_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parents_mec', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mechanism',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanismGroup',
            fields=[
                ('mechanism_group_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mechanism_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('type_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'type_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=50)),
                ('reviewed', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
