# Generated by Django 3.2.12 on 2022-09-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogidice', '0003_bggdata_boardgame_boardgamecafe_bookmark_cafegamelist_category_categorygroup_history_mechanism_mecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BggData',
        ),
        migrations.DeleteModel(
            name='BoardGame',
        ),
        migrations.DeleteModel(
            name='BoardGameCafe',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='CafeGameList',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Mechanism',
        ),
        migrations.DeleteModel(
            name='MechanismGroup',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='TypeGroup',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
